#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# check dscl for users UID > 500
for u in $(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -readall /Local/Target/Users | grep RecordName | grep -v 'RecordName: _' | awk '{print $2}'); do
user_id=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u UniqueID | awk '{print $2}')
if [ $user_id -gt 500 ]; then
	user_home=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u NFSHomeDirectory | awk '{print $2}')
	if [ -e "${path_root}/${user_home}/Library/Preferences" ]; then
		defaults write  "${path_root}${user_home}/Library/Preferences/com.skype.skype.plist" SKAllowStealthUpgrade -bool false
		chown "${u}" "${path_root}${user_home}/Library/Preferences/com.skype.skype.plist"
	fi
fi
done

exit 0
