#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# it's awesome, its here https://github.com/munki/munkiwebadmin
# make this smarter eventually...not enough checks

# service account
dscl . create /Users/osx
dscl . create /Users/osx RealName "Server Account"
dscl . passwd /Users/osx tellevery1
dscl . create /Users/osx UniqueID 666
dscl . create /Users/osx PrimaryGroupID 80
dscl . create /Users/osx UserShell /bin/bash
dscl . create /Users/osx NFSHomeDirectory /var/osx
cp -R /System/Library/User\ Template/English.lproj /var/osx

# service group
dseditgroup -o create -n . osx
dseditgroup -o edit -a osx -t user osx

# service account preferences
defaults write /var/osx/Library/Preferences/com.googlecode.munki.munkiimport.plist "default_catalog" ""
defaults write /var/osx/Library/Preferences/com.googlecode.munki.munkiimport.plist "editor" "/usr/bin/nano"
defaults write /var/osx/Library/Preferences/com.googlecode.munki.munkiimport.plist "pkginfo_extension" ""
defaults write /var/osx/Library/Preferences/com.googlecode.munki.munkiimport.plist "repo_path" "/Volumes/Data/www/munki_repo"
defaults write /var/osx/Library/Preferences/com.googlecode.munki.munkiimport.plist "repo_url" "http://localhost/munki_repo"
# permissions
chown -R osx:staff /var/osx

# munki repo path, already set by ConfigureMunki
#mkdir -p "${path_root}/Volumes/Data/www/munki_repo";
#mkdir -p "${path_root}/Volumes/Data/www/munki_repo/catalogs";
#mkdir -p "${path_root}/Volumes/Data/www/munki_repo/manifests";
#mkdir -p "${path_root}/Volumes/Data/www/munki_repo/pkgs";
#mkdir -p "${path_root}/Volumes/Data/www/munki_repo/pkgsinfo";
# permissions
chown -R root:osx /Volumes/Data/www/munki_repo
chmod -R 775 /Volumes/Data/www/munki_repo

# daemon
chown root:wheel "/Library/LaunchDaemons/com.googlecode.munki.munkiwebadmin.plist"
chmod 644 "/Library/LaunchDaemons/com.googlecode.munki.munkiwebadmin.plist"

exit 0