#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc
device_build=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductBuildVersion) # 13A603 etc

# think about other languages, or better still stop editing the default template..not really "best practise".

defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" DidSeeCloudSetup -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" GestureMovieSeen none
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" LastSeenBuddyBuildVersion "${device_build}"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" LastSeenCloudProductVersion "${device_os}"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" LastPreLoginTasksPerformedVersion "${device_os}"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" LastPreLoginTasksPerformedBuild "${device_build}"

# think about looping dscl instead as user directories may be re-directed. use uid to get real users.

for USER_HOMES in "/Users"/*
do
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant DidSeeCloudSetup -bool TRUE
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant GestureMovieSeen none
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant LastSeenCloudProductVersion "${device_os}"
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant LastSeenBuddyBuildVersion "${device_build}" 
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant LastPreLoginTasksPerformedVersion "${device_os}"
	defaults write "${USER_HOMES}"/Library/Preferences/com.apple.SetupAssistant LastPreLoginTasksPerformedBuild "${device_build}"     
done

exit 0