#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# disable com.apple.dockfixup
# disable some default apps in the dock and use in conjunction with a dock template file.
# I hate this postinstall and everything about it, let users manage their own dock.
the_plist="${path_root}/Library/Preferences/com.apple.dockfixup.plist"
[[ -e "${the_plist}" ]] && mv "${the_plist}" "${the_plist}.${formatted_date}"

exit 0