#!/bin/bash

# configure payload, include variables /tmp/config
# configure payload, include /tmp/kcpassword.10.x.x

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
dev_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion) # 10.9.x etc

# source the dscl variables
. "${path_root}/tmp/config"

# payload
[[ -e "${path_root}/etc/kcpassword" ]] && mv -f "${path_root}/etc/kcpassword"{,."${formatted_date}"}
[[ -e "${path_root}/tmp/kcpassword.${dev_os}" ]] && mv -f "${path_root}/tmp/kcpassword.${dev_os}" "${path_root}/etc/kcpassword"
[[ -e "${path_root}/etc/kcpassword" ]] && chown root:wheel "${path_root}/etc/kcpassword"
[[ -e "${path_root}/etc/kcpassword" ]] && chmod 600 "${path_root}/etc/kcpassword"
[[ -e "${path_root}/etc/kcpassword.disabled" ]] && srm -f "${path_root}/etc/kcpassword.disabled"

# enable autlogin user
if [ -e "${path_root}/etc/kcpassword" ]; then
	the_plist="${path_root}/Library/Preferences/com.apple.loginwindow.plist"
	[[ ! -z "${short_name}" ]] && defaults write "${the_plist}" autoLoginUser -string "${short_name}"
	[[ -e "${the_plist}" ]] && chown root:wheel "${the_plist}"
	[[ -e "${the_plist}" ]] && chmod 644 "${the_plist}"
fi

# cleanup
[[ -e "${path_root}/tmp/config" ]] && srm -f "${path_root}/tmp/config"

exit 0
