#!/bin/bash

formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# Backup!
mkdir -p /System/Library/SecurityBackup
security authorizationdb read system.preferences.energysaver > "/System/Library/SecurityBackup/authorization.system.preferences.energysaver.plist.${formatted_date}"

exit 0