#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

# think about other languages, or better still stop editing the default template..not really "best practise".
/usr/libexec/PlistBuddy -c "Add :networkbrowser dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.sidebarlists.plist"
/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.sidebarlists.plist"
/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled bool true" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.sidebarlists.plist"
/usr/libexec/PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled true" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.sidebarlists.plist"

# loop user home directories
if [ "${path_root}" != "/" ]; then
	# non-booted volume
	# check dscl for users UID > 500
	for u in $(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -readall /Local/Target/Users | grep RecordName | grep -v 'RecordName: _' | awk '{print $2}'); do
	user_id=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${path_root}/${user_home}/Library/Preferences" ]; then
			/usr/libexec/PlistBuddy -c "Add :networkbrowser dict" "${path_root}${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties dict" "${path_root}${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled bool true" "${path_root}${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled true" "${path_root}${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			chown "${u}" "${path_root}${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
		fi
	fi
	done
	
else
	# booted volume
	# check dscl for users UID > 500
	for u in $(dscl . -ls /Users | grep -v '^_'); do
	user_id=$(dscl . -read /Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl . -read /Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${user_home}/Library/Preferences" ]; then
			/usr/libexec/PlistBuddy -c "Add :networkbrowser dict" "${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties dict" "${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Add :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled bool true" "${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			/usr/libexec/PlistBuddy -c "Set :networkbrowser:CustomListProperties:com.apple.NetworkBrowser.bonjourEnabled true" "${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
			chown "${u}" "${user_home}/Library/Preferences/com.apple.sidebarlists.plist"
		fi
	fi
	done
fi

exit 0