#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

# it's awesome, its here https://github.com/wdas/reposado
# make this smarter eventually...not enough checks

gcc

sudo defaults write "${path_root}/System/Library/LaunchDaemons/org.apache.httpd.plist" Disabled -bool false

cp -Rf "${path_root}/Library/WebServer/Documents/" "/Volumes/Data/www"
mv -f "${path_root}/Library/WebServer/Documents" "${path_root}/Library/WebServer/Documents.bak"
ln -s "${path_root}/Volumes/Data/www" "${path_root}/Library/WebServer/Documents"

cd "${path_root}/Volumes/Data/www"
git clone https://github.com/wdas/reposado.git

if [ -e "${path_root}/Volumes/Data" ]; then
	mkdir -p "${path_root}/Volumes/Data/www/reposado/html"
	mkdir -p "${path_root}/Volumes/Data/www/reposado/metadata"
fi

#sudo ./reposado/code/repoutil --configure

defaults write "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" RepoSyncLogFile "${path_root}/Volumes/Data/www/reposado/reposado_sync.log"
defaults write "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" LocalCatalogURLBase http://mbp2.local/reposado/html
defaults write "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" UpdatesMetadataDir /Volumes/Data/www/reposado/metadata
defaults write "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" UpdatesRootDir /Volumes/Data/www/reposado/html
defaults write "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" "AppleCatalogURLs" -array-add "http://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"

plutil -convert xml1 "${path_root}/Volumes/Data/www/reposado/code/preferences.plist"

chown -R root:wheel "${path_root}/Volumes/Data/www"
chmod -R 755 "${path_root}/Volumes/Data/www"

if [ "${path_root}" != "/" ]; then
	# non-booted volume
	echo "Complete"
else
	sudo apachectl start
fi

# test a client 
#sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CatalogURL "http://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"

exit 0