#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

# think about other languages, or better still stop editing the default template..not really "best practise".

defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" DidSeeCloudSetup -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.SetupAssistant.plist" LastSeenCloudProductVersion "${device_os}"

# loop user home directories
# to reverse this you have to also delete the com.apple.loginwindow.plist and loginwindow.plist files from the users prefs folder
if [ "${path_root}" != "/" ]; then
	echo "Not the boot volume."
	
	for u in $(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -readall /Local/Target/Users | grep RecordName | awk '{print $2}'); do
	user_id=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${path_root}/${user_home}/Library/Preferences" ]; then
			defaults write "${path_root}${user_home}/Library/Preferences/com.apple.SetupAssistant.plist" DidSeeCloudSetup -bool true
			defaults write "${path_root}${user_home}/Library/Preferences/com.apple.SetupAssistant.plist" LastSeenCloudProductVersion "${device_os}"
			chown "${u}" "${path_root}${user_home}/Library/Preferences/com.apple.SetupAssistant.plist"
		fi
	fi
	done
	
else

	for u in $(dscl . -ls /Users); do
	user_id=$(dscl . -read /Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl . -read /Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${user_home}/Library/Preferences" ]; then
			defaults write "${user_home}/Library/Preferences/com.apple.SetupAssistant.plist" DidSeeCloudSetup -bool true
			defaults write "${user_home}/Library/Preferences/com.apple.SetupAssistant.plist" LastSeenCloudProductVersion "10.9"
			chown "${u}" "${user_home}/Library/Preferences/com.apple.SetupAssistant.plist"
		fi
	fi
	done
	
fi

exit 0