#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //

# maybe launchctl load the launchagent if root is / ???

# ensure correct permissions for the LaunchDaemon
chown root:wheel "${path_root}/Library/LaunchDaemons/com.github.autopkg.cgerke-recipes.ssh.plist"
chmod 644 "${path_root}/Library/LaunchDaemons/com.github.autopkg.cgerke-recipes.ssh.plist"

# ensure correct permissions for the motd file
chown root:wheel "${path_root}/etc/motd"
chmod 644 "${path_root}/etc/motd"

exit 0
