#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# it's awesome, its here https://github.com/munki/munki
# make this smarter eventually...not enough checks

# munki repo path
mkdir -p "${path_root}/Volumes/Data/www/munki_repo";
mkdir -p "${path_root}/Volumes/Data/www/munki_repo/catalogs";
mkdir -p "${path_root}/Volumes/Data/www/munki_repo/manifests";
mkdir -p "${path_root}/Volumes/Data/www/munki_repo/pkgs";
mkdir -p "${path_root}/Volumes/Data/www/munki_repo/pkgsinfo";
# permissions
chown -R root:admin /Volumes/Data/www/munki_repo
chmod -R 775 /Volumes/Data/www/munki_repo

exit 0