#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

# it's awesome, its here https://github.com/munki/munki
# make this smarter eventually...not enough checks

mkdir "${path_root}/Volumes/Data/www/munki_repo";
mkdir "${path_root}/Volumes/Data/www/munki_repo/catalogs";
mkdir "${path_root}/Volumes/Data/www/munki_repo/manifests";
mkdir "${path_root}/Volumes/Data/www/munki_repo/pkgs";
mkdir "${path_root}/Volumes/Data/www/munki_repo/pkgsinfo";

if [ -e "${path_root}/Volumes/Data/www" ]; then
	cd "${path_root}/Volumes/Data/www"
	git clone https://github.com/jessepeterson/margarita.git
fi


# margarita
#sudo easy_install flask
ln -s "${path_root}/Volumes/Data/www/reposado/code/reposadolib" "${path_root}/Volumes/Data/www/margarita/reposadolib"
ln -s "${path_root}/Volumes/Data/www/reposado/code/preferences.plist" "${path_root}/Volumes/Data/www/margarita/preferences.plist"
#sudo python ./margarita/margarita.py

# modify this to point to the correct path
cp -f ./margarita/com.github.jessepeterson.margarita.plist /Library/LaunchDaemons/

#defaults write "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" StandardErrorPath "/Volumes/Data/www/margarita/margarita_err.log"
#defaults write "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" StandardOutPath "/Volumes/Data/www/margarita/margarita.log"

defaults delete "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" ProgramArguments
defaults write "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" ProgramArguments -array-add "/usr/bin/python" "/Volumes/Data/www/margarita/margarita.py"
chown root:wheel "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist"
chmod 644 "${path_root}/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist"
	

chown root:wheel /Library/LaunchDaemons/com.github.jessepeterson.margarita.plist
chmod 644 /Library/LaunchDaemons/com.github.jessepeterson.margarita.plist

exit 0