#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

# Booted?
if [ "${3}" != "/" ]; then
	# Disable GateKeeper
	/usr/bin/defaults write "${path_root}/var/db/SystemPolicy-prefs.plist" enabled -string no
else
	/usr/sbin/spctl --master-disable
fi

# Disable re-arm
/usr/bin/defaults write "${path_root}/Library/Preferences/com.apple.security.plist" GKAutoRearm -bool false

exit 0