#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

# think about other languages, or better still stop editing the default template..not really "best practise".
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.NetworkBrowser.plist" DisableAirDrop -bool YES

# loop user home directories
if [ "${path_root}" != "/" ]; then
	# non-booted volume
	# check dscl for users UID > 500
	for u in $(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -readall /Local/Target/Users | grep RecordName | grep -v 'RecordName: _' | awk '{print $2}'); do
	user_id=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl -f "${path_root}/var/db/dslocal/nodes/Default" localonly -read /Local/Target/Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${path_root}/${user_home}/Library/Preferences" ]; then
			defaults write "${path_root}${user_home}/Library/Preferences/com.apple.NetworkBrowser.plist" DisableAirDrop -bool YES
			chown "${u}" "${path_root}${user_home}/Library/Preferences/com.apple.NetworkBrowser.plist"
		fi
	fi
	done
	
else
	# booted volume
	# check dscl for users UID > 500
	for u in $(dscl . -ls /Users | grep -v '^_'); do
	user_id=$(dscl . -read /Users/$u UniqueID | awk '{print $2}')
	if [ $user_id -gt 500 ]; then
		user_home=$(dscl . -read /Users/$u NFSHomeDirectory | awk '{print $2}')
		if [ -e "${user_home}/Library/Preferences" ]; then
			defaults write "${user_home}/Library/Preferences/com.apple.NetworkBrowser.plist" DisableAirDrop -bool YES
			chown "${u}" "${user_home}/Library/Preferences/com.apple.NetworkBrowser.plist"
		fi
	fi
	done
fi

# test the implications of this
#if [ "${path_root}" != "/" ]; then
#	echo "Not a booted volume."
#else
#	ifconfig awdl0 down
#fi

exit 0