#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //

# maybe launchctl load the launchagent if root is / to avoid a reboot???

# ensure correct permissions for the LaunchAgent
chown root:wheel "${path_root}/Library/LaunchAgents/com.github.autopkg.cgerke-recipes.ard.plist"
chmod 644 "${path_root}/Library/LaunchAgents/com.github.autopkg.cgerke-recipes.ard.plist"

# ensure correct permissions for the vnc password file
chown root:wheel "${path_root}/Library/Preferences/com.apple.VNCSettings.txt"
chmod 600 "${path_root}/Library/Preferences/com.apple.VNCSettings.txt"

exit 0
