#!/bin/bash

formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string
# Security authorizationdb can only be run on a booted volume so let's test for it.
# Think about testing for OS version too when you have time (in case of deprecation etc).
if [ "${3}" != "/" ]; then
	exit 1
else
	# Backup!
	security authorizationdb read system.preferences.printing > "/etc/authorization.system.preferences.printing.plist.${formatted_date}"
	security authorizationdb read system.print.admin > "/etc/authorization.system.print.admin.plist.${formatted_date}"
	security authorizationdb read system.print.operator > "/etc/authorization.system.print.operator.plist.${formatted_date}"
fi

exit 0