#!/bin/bash

formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# Reposado, it's awesome, its here https://github.com/wdas/reposado
#/Library/Server/Web/Config/apache2/ReadMe.txt

# must sudo
if [[ $(id -u) -ne 0 ]]; then
  echo "Run this script with sudo, just to be safe."
  exit 1
fi

httpd -v

if [ -e "/Users/Shared/reposado" ]; then
	echo  "Can see reposado."
else
	echo  "Can't see reposado. Cloning."
	cd "/Volumes/Data/"
	git clone https://github.com/wdas/reposado.git
fi

#python /Users/Shared/reposado/setup.py build
#python /Users/Shared/reposado/setup.py install

if [ -e "/Library/Server/Web/Data/Sites/Default" ]; then
	ln -s "/Users/Shared/reposado" "/Library/Server/Web/Data/Sites/Default/reposado"
	# hack
	ln -s "/Users/Shared/reposado/html/content" "/Library/Server/Web/Data/Sites/Default/reposado/content"
else
	echo "Probably OSX Client."
	cp /etc/apache2/httpd.conf{,.$formatted_date}
	# gcc
	if [ ! -e "/Library/WebServer/Documents/reposado" ]; then
		touch "/Library/WebServer/Documents/.htaccess"
		chown _www "/Library/WebServer/Documents/.htaccess"
		echo "Linking Reposado."
		ln -s "/Users/Shared/reposado" "/Library/WebServer/Documents/reposado"
	fi
	sudo defaults write "/System/Library/LaunchDaemons/org.apache.httpd.plist" Disabled -bool false
	# Uncomment LoadModule rewrite_module libexec/apache2/mod_rewrite.so
	apachect restart
fi

#repoutil --configure
defaults write "/Users/Shared/reposado/code/preferences.plist" RepoSyncLogFile "/Users/Shared/reposado/reposado_sync.log"
defaults write "/Users/Shared/reposado/code/preferences.plist" LocalCatalogURLBase http://osx.local/reposado
defaults write "/Users/Shared/reposado/code/preferences.plist" UpdatesMetadataDir /Users/Shared/reposado/metadata
defaults write "/Users/Shared/reposado/code/preferences.plist" UpdatesRootDir /Users/Shared/reposado/html
#defaults write "/Users/Shared/reposado/code/preferences.plist" "AppleCatalogURLs" -array-add "http://swscan.apple.com/content/catalogs/index.sucatalog"
#defaults write "/Users/Shared/reposado/code/preferences.plist" "AppleCatalogURLs" -array-add "http://swscan.apple.com/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
plutil -convert xml1 "/Users/Shared/reposado/code/preferences.plist"
chown -R root:wheel "/Users/Shared/reposado"
chmod -R 755 "/Users/Shared/reposado"

export PATH=$PATH:"/Users/Shared/reposado":"/Users/Shared/reposado/code"

# Sync
#repo_sync

# Create a new branch
#repoutil --new-branch testing

# Check what products are available
#repoutil --products

# Margarita, it's awesome, its here https://github.com/jessepeterson
cd /Users/Shared/
git clone https://github.com/jessepeterson/margarita.git
easy_install flask
cp -f "/Users/Shared/margarita/com.github.jessepeterson.margarita.plist" /Library/LaunchDaemons/
defaults delete "/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" ProgramArguments
defaults write "/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist" ProgramArguments -array-add "/usr/bin/python" "/Users/Shared/margarita/margarita.py"
chown root:wheel "/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist"
chmod 644 "/Library/LaunchDaemons/com.github.jessepeterson.margarita.plist"
ln -s "/Users/Shared/reposado/code/reposadolib" "/Users/Shared/reposadolib"
ln -s "/Users/Shared/reposado/code/preferences.plist" "/Users/Shared/margarita/preferences.plist"


exit 0

# Add some products to testing
#repoutil --add-product 041-0560 zzzz041-0565 zzzz041-0531 zzzz041-0532 testing

# Configure a client
softwareupdate -l --set-catalog "http://osx.local/reposado/html/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1_testing.sucatalog"
# or default branch
#softwareupdate -l --set-catalog "http://osx.local/reposado/html/content/catalogs/others/index-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.apple"