#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi #++ fix //
# Security authorizationdb can only be run on a booted volume so let's test for it.
# Think about testing for OS version too when you have time (in case of deprecation etc).
if [ "${path_root}" != "/" ]; then
	exit 1
else
	# Authorization to allow non-admin users to modify the Printers & Scanners PreferencePane.
	# There's a few ways to do this, a popular way is to create a "PowerUsers" group and add the group as an Authorization
	# in my environment I want everyone to do as they please.
	security authorizationdb write system.preferences allow
	security authorizationdb write system.preferences.printing allow
	security authorizationdb write system.print.admin allow
	security authorizationdb write system.print.operator allow
	# Modify lpadmins
	dseditgroup -o edit -a everyone -t group lpadmin
fi

exit 0