#!/bin/bash

formatted_date=$(date +"%Y%m%d%H%M%S") #++ date to string

# Security authorizationdb can only be run on a booted volume so let's test for it.
# Think about testing for OS version too when you have time (in case of deprecation etc).
if [ $3 != "/" ]; then
	exit 1
else
	# Backup!
	mkdir -p /System/Library/SecurityBackup
	security authorizationdb read system.preferences.printing > "/System/Library/SecurityBackup/authorization.system.preferences.printing.plist.${formatted_date}"
	security authorizationdb read system.print.admin > "/System/Library/SecurityBackup/authorization.system.print.admin.plist.${formatted_date}"
	security authorizationdb read system.print.operator > "/System/Library/SecurityBackup/authorization.system.print.operator.plist.${formatted_date}"
fi

exit 0